[package]
name = "cloudbit_software"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = "0.2.13"
futures = "0.3.30"
json = "0.12.4"
serde = "1.0.197"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["rt", "macros"] }
tokio-tungstenite = { version = "0.21.0", features = ["rustls", "tokio-rustls"] }
# openssl = { version = "0.10.64", features = ["vendored"] }
toml = "0.8.10"
tungstenite = { version = "0.21.0", features = ["rustls"] }
url = "2.5.0"

[[bin]]
name = "cloud_client"
path = "src/main.rs"
