[package]
name = "cloudbit-software"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = "0.2.13"
json = "0.12.4"
tungstenite = { version = "0.21.0", features = ["native-tls", "rustls"] }

[[bin]]
name = "cloudbit-software"
path = "main.rs"
