[package]
name = "cloudbit_software"
description = "alternate software for the littleBits cloudBit"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0-or-later"
readme = true
repository = "https://github.com/littlebitsman/cloudbit-software"

exclude = ["/.cargo/*", "/.github/*", "/.gitignore", "/files/*", "/testServer/*", "/buildtools/*"]

[dependencies]
futures = "0.3.30"
libc = "0.2.158"
mac_address = "1.1.7"
sysinfo = { version = "0.31.2", default-features = false, features = ["system"] }
serde = { version = "1.0.208", default-features = false }
serde_json = "1.0.125"
tokio = { version = "1.39.3", features = ["rt", "macros", "rt-multi-thread", "time"] }
tokio-tungstenite = { version = "0.23.1", features = ["rustls-tls-webpki-roots", "tokio-rustls"] }
url = "2.5.2"

[[bin]]
name = "cloud_client"
path = "src/main.rs"

[profile.release]
strip = "debuginfo"
lto = "thin"
