[package]
name = "cloudbit-software"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = "0.2.13"
json = "0.12.4"

[[bin]]
name = "cloud_client"
path = "src/main.rs"
