[package]
name = "cloudbit_software"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
execute = "0.2.13"
futures = "0.3.30"
libc = "0.2.155"
mac_address = "1.1.5"
sysinfo = { version = "0.30.12", default-features = false, features = ["serde"] }
serde = { version = "1.0.197", default-features = false }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["rt", "macros", "rt-multi-thread", "time"] }
tokio-tungstenite = { version = "0.23.0", features = ["rustls-tls-webpki-roots", "tokio-rustls"] }
url = "2.5.0"

[[bin]]
name = "cloud_client"
path = "src/main.rs"

[profile.release]
strip = "debuginfo"
lto = "thin"