name: Audit

on:
  push:
    branches: [ "main", "udp" ]
  pull_request:
    branches: [ "main", "udp" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install audit tools
      run: cargo install cargo-audit
    - name: Audit
      run: cargo audit
