name: Audit

on:
  push:
    
  pull_request:

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install audit tools
      run: cargo install cargo-audit --features=fix
    - name: Audit
      id: step-audit
      continue-on-error: true
      run: cargo audit
    - name: Fix vulnerabilities
      if: ${{ failure() && steps.step-audit.outcome == 'failure' }}
      run: cargo audit fix
