name: Audit

on:
  push:
    
  pull_request:

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install audit tools
      run: cargo install cargo-audit --features=fix
    - name: Audit
      id: step-audit
      run: cargo audit
    - name: Fix vulnerabilities
      if: ${{ steps.step-audit.conclusion == "success" }}
      run: cargo audit fix
