name: Releases

on:
  push:
    tags: [ "v*.*.*" ]
    paths: ["src", "src/**"]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.ref_name != 'main' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Build
      uses: houseabsolute/actions-rust-cross@v0
      with:
        target: armv5te-unknown-linux-musleabi
        args: --release
    - name: Rename file
      run: mv ./target/armv5te-unknown-linux-musleabi/release/cloud_client ./cloud_client
    - name: Upload output file
      uses: actions/upload-artifact@v4
      with: 
        name: cloud_client
        path: ./cloud_client
    - name: Push build
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -a -m "build"
        git push
  release:
    runs-on: ubuntu-latest
    if: github.ref_name
    needs: build
    steps: 
      - name: Get artifacts
        uses: actions/download-artifact@v4.1.7
        with: 
          name: cloud-client
          path: ./
      - name: Publish
        uses: softprops/action-gh-release@v2
        with: 
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: ./cloud_client
