name: Rust

on:
  push:
    branches: [ "main" ]
    paths: ["src", "src/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["src", "src/**"]
    
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: cargo install cross; rustup target add armv5te-unknown-linux-musleabi
    - name: Build
      run: cross build --release --target armv5te-unknown-linux-musleabi
    - name: Run tests
      run: cargo test --verbose
    - name: Push build
      run: |
        mv target/armv5te-unknown-linux-musleabi/release/cloud_client ./
        git commit -a -m "build"
        git push
